### ISSUE TITLE
Can't update custom user field using the provided api object

### ISSUE THREAD

**Issue by lvisintini** [facetoe/zenpy#93] opened 2017-01-23 16:52 UTC
Given that a user is found by the following snippet:
```
>>> # Version 1.1.9-1
>>> zenpy = Zenpy(**settings.ZENDESK_CREDENTIALS)
>>> user = zenpy.search(type='user', email='myemail@example.com').next()
```
I would like to able to update that user by modifying the returned object.

Doing ``user.to_dict()`` provides me with the data I want, with the custom ``user_fields`` dict.

All is good and well, but I could not find a way to make any changes to those fields by making use of the generator object provided by ``user.user_fields``

An error is raised if I try to iterate through it:
```
>>> user.user_fields
<generator object _get_fields at 0x7fb89bd39370>
>>> for x in user.user_fields:
...     print x
... 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/zenpy/lib/api.py", line 248, in _get_fields
    if any([self._query_cache(object_type, field) is None for field in [f['id'] for f in fields]]):
TypeError: string indices must be integers
>>> user.user_fields.next()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/zenpy/lib/api.py", line 248, in _get_fields
    if any([self._query_cache(object_type, field) is None for field in [f['id'] for f in fields]]):
TypeError: string indices must be integers
```

The only why that I have managed to do what I wanted was to be nasty and update the protected``_user_fields`` property:
```
>>> user._user_fields
{u'my_field': 1032}
>>> user._user_fields['user_id'] = 1030
>>> zenpy.users.update(user)
```

For a workaround, it works well, but would be nice not manipulate that property directly.

Cheers

Luis

**Comment by facetoe** [comment] 2017-01-23 18:22
Thanks for the report @lvisintini, this is a bug. I've pushed a fix and you should now be able to update a user's user fields like so:

```python
user = zenpy_client.users(id=18021868088)
user.user_fields.update(dict(some_field='some value'))
zenpy_client.users.update(user)
```  

Let me know if you have any trouble!

**Comment by lvisintini** [comment] 2017-01-24 16:56
Any ETA for this to be available through pip? (no rush)

**Comment by facetoe** [comment] 2017-01-24 23:32
No worries, I've pushed a new version (1.1.10) to Pypi.

**Comment by dlasusa** [comment] 2018-02-27 22:50
Hi, I'm new to Github, Python and Zenpy, so please forgive any dumb as well syntax error while trying to ask this question (or if it should be a new question - since it was related to the post above I'm commenting here, let me know if it should go elsewhere)

Is the method listed above still the correct/working way to update custom user fields?

This works and returns expected values:
`for user in zenpy_client.users(): `
&nbsp;&nbsp;&nbsp;&nbsp;`print(user.user_fields.to_dict())`

**Result:**
{'title': 'best title ever', 'location': 'Earth', 'phone': 5551212, 'program': 'blah!'}

But when I try to update based on the post above:
`user.user_fields.update(dict(location='Mars'))`
`zenpy_client.users.update(user)`

**Result:**
Traceback (most recent call last):
user.user_fields.update(dict(location='Mars'))
AttributeError: 'UserField' object has no attribute 'update'

Since I'm new to Python this may not make ANY sense, but I also tried:
`user.user_fields.dict(location='Mars')`
`zenpy_client.users.update(user)`

**Result:**
AttributeError: 'UserField' object has no attribute 'dict'

and

`user.user_fields(location='Mars')`
`zenpy_client.users.update(user)`

**Result:**
TypeError: 'UserField' object is not callable

I also tried:
`user.user_fields.program = 'dan'`
`zenpy_client.users.update(user)`

Which seems to update the object in my script but the change is not written back to Zendesk.

I'm not sure what I might be missing.

Thanks for any help!

**Comment by facetoe** [comment] 2018-02-28 10:44
Hi @dlasusa, thanks for the report. You are doing everything right, looks like this is a regression that snuck in at some point. 

Until I can push a fix you can use the following workaround:

```python
user = zenpy_client.users.me()
user.user_fields = dict(field_key='field value')
zenpy_client.users.update(user)
```

**Comment by dlasusa** [comment] 2018-02-28 18:25
@facetoe 
That work workaround worked perfectly!!  Thank you!

**Closed** 2018-03-24 19:11 UTC
Labels: bug
