### ISSUE TITLE
502 Server Error: Bad Gateway when trying to upload attachment

### ISSUE THREAD

**Issue by Simon-Ince** [facetoe/zenpy#382] opened 2019-12-05 11:30 UTC
I'm getting: `requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://lushltd.zendesk.com/api/v2/uploads.json?filename=/app/joel.jpg`

From running: `upload_instance = zenpy_client.attachments.upload("/app/joel.jpg")`

Weird thing is, this was working for me yesterday. I've checked the ZenDesk API status and everything is up, and there Docs don't say anything about any changes to upload files.

I did find this issue that is similar, but there was no real resolution: https://app.slack.com/client/T029C5TRD/D9MF3DTB8

**Comment by maxdandan** [comment] 2019-12-06 07:11
Same for me.
i got 502 or 500 when uploading attachment

**Comment by Simon-Ince** [comment] 2019-12-10 12:40
I was on 2.0.15, I've just tried 2.0.10 and can now upload.

**Comment by facetoe** [comment] 2019-12-13 23:25
Do you guys still have this issue on the latest Zenpy? I've been unable to reproduce it and am thinking it may have been a temporary Zendesk issue.

**Comment by facetoe** [comment] 2019-12-19 10:17
Closing as doesn't seem to be an ongoing issue.

**Comment by gaige** [comment] 2019-12-20 19:28
@facetoe I just had this reported yesterday when running 2.0.13. I tried upgrading to 2.0.16 and  the problem (502 errors) persisted when uploading files.  I rolled back to 2.0.10 as others indicated and the problem went away. 

I can use `curl` to call the URL directly and don't seem to run into any specific problems.

**Closed** 2020-01-12 03:36 UTC
Labels: question
