### ISSUE TITLE
Incorrect Jira Issue Number when retrieving them via jira_links

### ISSUE THREAD

**Issue by xd3262nd** [facetoe/zenpy#418] opened 2020-04-23 16:21 UTC
Hello, 

I have noticed a few of my responses when calling `jira_links` is not providing the right Jira issue number. On the UI it shows the right Jira number but when I print out the result with `jira_links` the Jira issue number changed to something else. Is it something wrong with the API call? or there is some errors on the UI?

**Comment by jwalterclark** [comment] 2020-04-23 18:12
Can you provide an example?

One thing I'll note up front is that the Jira ID number (`issue_id`) is different from the Jira key (`issue_key`).  The key is what you will see in the UI and the ID is a unique number that Jira uses behind the scenes.

**Comment by xd3262nd** [comment] 2020-04-23 18:20
Yeap, and I double-check the Jira ID number and the Jira Key (retrieve from `zenpy`) is different from the ZenDesk UI. 

For example: 
In my UI, the Jira issue that was linked to the ZD ticket has the key to `QW-123` and id of `1234`. 
But when I retrieved the Jira Key and Jira ID with `jira_links` it shows me `ZX-390` and id of `7843`. And I tried to retrieve the `ZX-390` or `7843` from my Jira UI, I couldn't find the issue at all. Instead I can find the `QW-123` issue on my Jira.

**Comment by jwalterclark** [comment] 2020-04-23 18:53
What does the code look like?

**Comment by xd3262nd** [comment] 2020-04-23 19:14
```
for j in zenpy_client.jira_links():
  ticket_id = str(j.ticket_id)
  issue_id = j.issue_id
```
Do you think is might caused by changing the Jira Issue Name after linking to the Zendesk Ticket?

**Comment by jwalterclark** [comment] 2020-04-23 21:00
I'm not sure about the issue name. Maybe if it moved from one Jira project to another, but I think the integration is supposed to [automatically sync field changes](https://support.zendesk.com/hc/en-us/articles/115004257108#topic_ith_yzh_2z).

Something you can do to troubleshoot is look at the Jira API for those issue IDs and make sure the results align with your expectations. You can do this in your browser- just log into Jira and then open links like these.

```
https://{subdomain}.atlassian.net/rest/api/3/issue/1234
https://{subdomain}.atlassian.net/rest/api/3/issue/7843
```

Then you can pull the corresponding link from Zendesk and validate whether the data is out of sync.

```
curl -u {email_address}:{password} \
  'https://{subdomain}.zendesk.com/api/services/jira/links?issue_id=1234'

curl -u {email_address}:{password} \
  'https://{subdomain}.zendesk.com/api/services/jira/links?issue_id=7843'
```

**Comment by xd3262nd** [comment] 2020-04-24 14:28
Oh thanks for the tips ( I am very new to all the API thing). And I found out it is indeed out of sync. Would you mind to teach me how to correct it? or update it?

**Comment by sivanov-nuodb** [comment] 2020-04-30 11:05
I have the same problem and it is a regression in 2.0.18+ caused by PR-389 (https://github.com/facetoe/zenpy/pull/389).

Sample code to reproduce:
```
        jiraLinkResults = zenpyClient.jira_links(ticket_id=ticket.id)
        jiraIssues = []
        for link in jiraLinkResults:
                logger.debug("Got JIRA issue %s for ticket %s", link.issue_key, ticket.id)
```

This is logging from Zenpy 2.0.19 (latest version):
```
INFO - Analyzing ticket yyyy ...
DEBUG - GET: https://xxxx.zendesk.com/api/services/jira/links.json?ticket_id=yyyy - {'timeout': 60.0}
DEBUG - GenericZendeskResponseHandler matched: {'links': [{'id': 15292496, 'ticket_id': 'yyyy', 'issue_id': '56697', 'issue_key': 'zzzz', 'url': 'https://xxxx.zendesk.com/api/services/jira/links/15292496', 'created_at': '2020-04-21T14:02:19.000Z', 'updated_at': '2020-04-21T15:08:33.000Z'}], 'total': 1}
DEBUG - Got JIRA issue zzzz for ticket yyyy
DEBUG - GET: https://xxxx.zendesk.com/api/services/jira/links - {'timeout': 60.0, 'params': {'since_id': 15292496}}
DEBUG - Got JIRA issue kkkk for ticket yyyy
DEBUG - Got JIRA issue eeee for ticket yyyy
DEBUG - Got JIRA issue kkkk for ticket yyyy
...
DEBUG - GET: https://xxxx.zendesk.com/api/services/jira/links - {'timeout': 60.0, 'params': {'since_id': 15428746}}
...
```

This is logging from Zenpy 2.0.17 (latest version):
```
INFO - Analyzing ticket yyyy ...
DEBUG - GET: https://xxxx.zendesk.com/api/services/jira/links.json?ticket_id=yyyy - {'timeout': 60.0}
DEBUG - GenericZendeskResponseHandler matched: {'links': [{'id': 15292496, 'ticket_id': 'yyyy', 'issue_id': '56697', 'issue_key': 'zzzz', 'url': 'https://xxxx.zendesk.com/api/services/jira/links/15292496', 'created_at': '2020-04-21T14:02:19.000Z', 'updated_at': '2020-04-21T15:08:33.000Z'}], 'total': 1}
DEBUG - Got JIRA issue zzzz for ticket yyyy
```

Note: The only valid link in Zendesk is between ticketId yyyy and Jira issue key zzzz. 

To me, it looks like the `JiraLinkGenerator` does not have a condition when to stop the pagination.
I hope that this helps to narrow down the problem.

**Comment by jwalterclark** [comment] 2020-04-30 15:23
Thanks for the repro steps, @sivanov-nuodb ! That really was helpful.

I think your issue is that your version is actually out of date and you're experiencing https://github.com/facetoe/zenpy/issues/400. This should be fixed by https://github.com/facetoe/zenpy/pull/413.

```
ticket_1 = zd.tickets(id={ticket_id_1}) # Has 3 links

jiraLinkResults = zd.jira_links(ticket_id=ticket_1.id)
DEBUG - GET: https://{subdomain}.zendesk.com/api/services/jira/links.json?ticket_id={ticket_id_1} - {'timeout': 60.0}
DEBUG - https://{subdomain}.zendesk.com:443 "GET /api/services/jira/links.json?ticket_id={ticket_id_1} HTTP/1.1" 200 None
DEBUG - GenericZendeskResponseHandler matched: {'links': [{'id': {link_id_1}, 'ticket_id': '{ticket_id_1}', 'issue_id': '{issue_id_1}', 'issue_key': '{issue_key_1}', 'url': 'https://{subdomain}.zendesk.com/api/services/jira/links/{link_id_1}', 'created_at': '{redacted}', 'updated_at': '{redacted}'}, {'id': {link_id_2}, 'ticket_id': '{ticket_id_1}', 'issue_id': '{issue_id_2}', 'issue_key': '{issue_key_2}', 'url': 'https://{subdomain}.zendesk.com/api/services/jira/links/{link_id_2}', 'created_at': '{redacted}', 'updated_at': '{redacted}'}, {'id': {link_id_3}, 'ticket_id': '{ticket_id_1}', 'issue_id': '{issue_id_3}', 'issue_key': '{issue_key_3}', 'url': 'https://{subdomain}.zendesk.com/api/services/jira/links/{link_id_3}', 'created_at': '{redacted}', 'updated_at': '{redacted}'}], 'total': 3}

for link in jiraLinkResults:
        logger.debug("Got JIRA issue %s for ticket %s", link.issue_key, ticket_1.id)
DEBUG - Got JIRA issue {issue_key_1} for ticket {ticket_id_1}
DEBUG - Got JIRA issue {issue_key_2} for ticket {ticket_id_1}
DEBUG - Got JIRA issue {issue_key_3} for ticket {ticket_id_1}
DEBUG - GET: https://{subdomain}.zendesk.com/api/services/jira/links.json?ticket_id={ticket_id_1}&since_id={link_id_3} - {'timeout': 60.0}
DEBUG - https://{subdomain}.zendesk.com:443 "GET /api/services/jira/links.json?ticket_id={ticket_id_1}&since_id={link_id_3} HTTP/1.1" 200 None


ticket_2 = zd.tickets(id=ticket_id_2) # Has 1 link

jiraLinkResults = zd.jira_links(ticket_id=ticket_2.id)
DEBUG - GET: https://{subdomain}.zendesk.com/api/services/jira/links.json?ticket_id={ticket_id_2} - {'timeout': 60.0}
DEBUG - https://{subdomain}.zendesk.com:443 "GET /api/services/jira/links.json?ticket_id={ticket_id_2} HTTP/1.1" 200 None
DEBUG - GenericZendeskResponseHandler matched: {'links': [{'id': {link_id_4}, 'ticket_id': '{ticket_id_2}', 'issue_id': '{issue_id_4}', 'issue_key': '{issue_key_4}', 'url': 'https://{subdomain}.zendesk.com/api/services/jira/links/{link_id_4}', 'created_at': '{redacted}', 'updated_at': '{redacted}'}], 'total': 1}

for link in jiraLinkResults:
        logger.debug("Got JIRA issue %s for ticket %s", link.issue_key, ticket_2.id)
DEBUG - Got JIRA issue {issue_key_4} for ticket {ticket_id_2}
DEBUG - GET: https://{subdomain}.zendesk.com/api/services/jira/links.json?ticket_id={ticket_id_2}&since_id={link_id_4} - {'timeout': 60.0}
DEBUG - https://{subdomain}.zendesk.com:443 "GET /api/services/jira/links.json?ticket_id={ticket_id_2}&since_id={link_id_4} HTTP/1.1" 200 None
```

Can you try a `pip uninstall zenpy` and then a `pip install zenpy`? I didn't submit a version bump when I submitted https://github.com/facetoe/zenpy/pull/413.

@facetoe - looking at the commit history it looks like you usually do the version bump. Can I ask you for some guidance on your preference? I'll happily increment the point version if I happen to send another PR, but I want to defer to you.

**Comment by sivanov-nuodb** [comment] 2020-04-30 15:50
@jwalterclark Thanks for the quick update!
It does look like fixed by #413. Thanks for pointing to the originally reported issue (#400).
I already tried using `pip uninstall zenpy` followed by `pip install zenpy` both in and outside of python virtual environment and this didn't download the latest code from master branch. Not sure if you need to bump up the version or not.

**Comment by facetoe** [comment] 2020-05-02 00:11
Yep it's probably time to push a new release

**Comment by facetoe** [comment] 2020-05-31 00:59
OK pushed a new release - https://github.com/facetoe/zenpy/releases/tag/2.0.20

**Closed by facetoe** 2020-05-31 00:59 UTC
Labels: question
